services:
  api:
    build:
      context: .. # Project racine
      dockerfile: docker/Dockerfile
    image: homelab-maker
    container_name: homelab-maker
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../config:/config:rw
    environment:
      - PYTHONUNBUFFERED=1